### ISSUE TITLE
Issues on Zesty

### ISSUE THREAD

**Issue by katronix** [devrandom/gitian-builder#145] opened 2017-07-07 19:43 UTC
Trying to install this on Ubuntu Zesty (17.04) and when I execute the command 
**sudo bin/make-base-vm**

I get the following:

Setting up dh-python (2.20151103ubuntu1.1) ...
Setting up distro-info-data (0.28ubuntu0.3) ...
Setting up eject (2.1.5+deb1+cvs20081104-13.1ubuntu0.16.04.1) ...
Setting up libisc-export160 (1:9.10.3.dfsg.P4-8ubuntu1.7) ...
Setting up libdns-export162 (1:9.10.3.dfsg.P4-8ubuntu1.7) ...
Setting up isc-dhcp-client (4.3.3-5ubuntu12.7) ...
Setting up isc-dhcp-common (4.3.3-5ubuntu12.7) ...
Setting up less (481-2.1ubuntu0.2) ...
Setting up libnettle6:amd64 (3.2-1ubuntu0.16.04.1) ...
Setting up libhogweed4:amd64 (3.2-1ubuntu0.16.04.1) ...
Setting up libidn11:amd64 (1.32-3ubuntu1.1) ...
Setting up libp11-kit0:amd64 (0.23.2-5~ubuntu16.04.1) ...
Setting up libtasn1-6:amd64 (4.7-3ubuntu0.16.04.2) ...
Setting up libgnutls30:amd64 (3.4.10-4ubuntu1.3) ...
Setting up libgnutls-openssl27:amd64 (3.4.10-4ubuntu1.3) ...
Setting up resolvconf (1.78ubuntu4) ...
Setting up sudo (1.8.16-0ubuntu1.4) ...

Configuration file '/etc/sudoers'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** sudoers (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package sudo (--configure):
 end of file on stdin at conffile prompt
Setting up vim-common (2:7.4.1689-3ubuntu1.2) ...
Setting up vim-tiny (2:7.4.1689-3ubuntu1.2) ...
Setting up kbd (1.15.5-1ubuntu5) ...
Setting up console-setup-linux (1.108ubuntu15.3) ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-1.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-13.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-14.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-15.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-2.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-3.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-4.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-7.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-9.inc ...
Setting up console-setup (1.108ubuntu15.3) ...
Your console font configuration will be updated the next time your system
boots. If you want to update it now, run 'setupcon' from a virtual console.
update-initramfs: deferring update (trigger activated)
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for systemd (229-4ubuntu17) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for initramfs-tools (0.122ubuntu8.8) ...
update-initramfs: Generating /boot/initrd.img-4.4.0-83-generic
Processing triggers for resolvconf (1.78ubuntu4) ...
Errors were encountered while processing:
 sudo
Extracting templates from packages: 100%
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by devrandom** [comment] 2017-07-24 00:16
Is this a duplicate of #144?

**Closed** 2017-07-24 00:17 UTC
