### ISSUE TITLE
Error updating sudoers while creating trusty kvm base image

### ISSUE THREAD

**Issue by laanwj** [devrandom/gitian-builder#144] opened 2017-02-20 11:00 UTC
(reported against master as of ad3f9cc)
While creating the KVM base image:
```bash
bin/make-base-vm --arch amd64 --suite trusty
```
We now get the error:
```
Configuration file '/etc/sudoers'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** sudoers (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package sudo (--configure):
 EOF on stdin at conffile prompt
invoke-rc.d: policy-rc.d denied execution of restart.
Errors were encountered while processing:
 sudo
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
This does not happen when creating the LXC base image. 

It does not appear to be a specific problem to my setup: At least @jonasschnelli and I have both encountered this, and it has been reported in #139 (closed) previously.

I think some silent/"do not prompt" flag is missing in the initial apt upgrade.

**Comment by achow101** [comment] 2017-02-20 13:51
This is an issue with vmbuilder. See https://bugs.launchpad.net/vmbuilder/+bug/1659952

**Comment by jonasschnelli** [comment] 2017-02-20 14:37
The fix mentioned in the VMBuilder bug report (see link in the comment from @achow101 above) worked for me:

```
self.run_in_target('apt-get', '-y', '--force-yes', 'dist-upgrade',

and replace with:

self.run_in_target('apt-get', '-y', '--force-yes', '--option=Dpkg::Options::=--force-confnew', 'dist-upgrade',
```

**Comment by laanwj** [comment] 2017-02-20 14:40
Thanks. I wonder if installing a newer vmbuilder would work. Currently we direct people at installing vmbuilder "vm-builder_0.12.4+bzr494.orig.tar.gz" at https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md#installing-gitian

But this version is kind of old by now.

**Comment by unsystemizer** [comment] 2017-02-20 14:49
We had this in https://github.com/devrandom/gitian-builder/issues/139#issuecomment-275669048
This is one of several reasons why I created https://github.com/bitcoin/bitcoin/issues/9636.

**Comment by laanwj** [comment] 2017-02-20 15:26
@unsystemizer In that issue you recommend people to use KVM instead of LXC for no clear reason. I don't see why it would be a solution to this problem, which occurs only with KVM.

**Comment by josephbisch** [comment] 2017-02-24 18:29
From the vmbuilder bug report link, you can find [the merge request](https://code.launchpad.net/~vanzhiganov/vmbuilder/vmbuilder/+merge/315834) that has been approved but not yet merged.

So "vm-builder_0.12.4+bzr494.orig.tar.gz" is actually still the newest version of vmbuilder if you only consider the main vmbuilder branch, and therefore, the issue isn't fixed yet in "official" vmbuilder.

This issue is in large part why I opened https://github.com/devrandom/gitian-builder/issues/143. Though it is nice to see someone trying to fix issues in upstream vmbuilder rather than a fork.

**Comment by unsystemizer** [comment] 2017-04-06 09:58
@laanwj, no, that's a fix for the KVM part I found while working on the part of the document that I *do* want to recommend (KVM). 

My reasons against LXC are that even after trying many times I never found a way to get it to work based on the instructions, so what I could do sooner is improve the KVM part first and recommend it until the LXC part was fixed.  

I am not against multiple approaches.  In fact I hope to contribute improvements to the LXC part as well - I just thought the community would benefit from incremental improvements rather than wait until someone fixes the both "tracks" (KVM/LXC). 

And if we knew that the KVM part of the document was fixed it'd make sense to recommend it until the LXC track is fixed - why not let the reader know that the LXC instructions don't work? - at which point the recommendation could be removed.  

But I saw your comment in the Bitcoin repo so I am okay with any approach that will result in a usable Gitian build procedure for non-developers which we currently don't have.

**Comment by laanwj** [comment] 2017-04-06 10:32
Yes. Having choice of LXC and KVM makes sense.

I just mean that LXC is *conceptually* the way to go. It just abstracts the environment in a deterministic containe.. Running a whole kernel+OS in a virtual machine is overkill for  building software. No matter what is currently easier to use, for the future of deterministic building we'll more likely go toward a thinner abstraction than a thicker one.

**Comment by Sjors** [comment] 2017-07-23 17:37
Fwiw, [this](https://stackoverflow.com/a/44041908) also made the error go away.

**Closed** 2017-12-22 23:36 UTC
