### ISSUE TITLE
dpkg erros processing sudo and ubuntu-minimal

### ISSUE THREAD

**Issue by lucaszanella** [devrandom/gitian-builder#167] opened 2018-02-15 20:07 UTC
Am I doing something wrong? Tried with sudo and without sudo. 

Also, a strange effect happens: whenever I press control C, my system logs off. Happened in my 2 computers after trying to install gitian 

This is the output of `bin/make-base-vm --arch amd64`
```
...
Configuration file '/etc/sudoers'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** sudoers (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package sudo (--configure):
 end of file on stdin at conffile prompt
Setting up vim-common (2:7.4.1689-3ubuntu1.2) ...
Setting up vim-tiny (2:7.4.1689-3ubuntu1.2) ...
dpkg: dependency problems prevent configuration of ubuntu-minimal:
 ubuntu-minimal depends on sudo; however:
  Package sudo is not configured yet.

dpkg: error processing package ubuntu-minimal (--configure):
 dependency problems - leaving unconfigured
Setting up kbd (1.15.5-1ubuntu5) ...
Setting up console-setup-linux (1.108ubuntu15.3) ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-1.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-13.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-14.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-15.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-2.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-3.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-4.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-7.inc ...
Installing new version of config file /etc/console-setup/compose.ISO-8859-9.inc ...
Setting up console-setup (1.108ubuntu15.3) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for systemd (229-4ubuntu21.1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for initramfs-tools (0.122ubuntu8.10) ...
update-initramfs: Generating /boot/initrd.img-4.4.0-112-generic
Processing triggers for resolvconf (1.78ubuntu6) ...
Errors were encountered while processing:
 sudo
 ubuntu-minimal
Extracting templates from packages: 100%
W: --force-yes is deprecated, use one of the options starting with --allow instead.
W: Can't drop privileges for downloading as file '/var/cache/apt/archives/partial/base-files_9.4ubuntu4.5_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by josephbisch** [comment] 2018-02-15 23:17
The only place that gitian itself appears to mess around with `/etc/sudoers*` is [here in gbuild](https://github.com/devrandom/gitian-builder/blob/e2172de865fe5d3b039e92844bcd1ae830e12cd2/bin/gbuild#L75), but that is with a file under `/etc/sudoers.d/` not with `/etc/sudoers` itself, so that doesn't explain why dpkg believes that `/etc/sudoers` is modified. This must be a bug with vmbuilder or our usage of vmbuilder. Vmbuilder probably adds the default vmbuilder user to `/etc/sudoers`, and then this upgrade of the sudo package includes a modified version of `/etc/sudoers`, so we are prompted to make a choice, but can't. We can use `-o DPkg::Options::="--force-confnew"` or `-o DPkg::Options::="--force-confold"` to force the selection of the new or old file respectively, but I don't know if either choice is correct here. We probably want the new file with our changes merged in.

Thanks for reporting the bug.

Also, I don't know why you are being logged off after pressing control C. When using LXC, I've had alt plus the left or right arrow key change my virtual terminal, which may appear like you've been logged out, but you just need to change back to the correct virtual terminal. But you don't appear to be using LXC and that wasn't with control C for me. When does this occur? Is it after you clone the gitian-builder repo? Or after you run make-base-vm?

**Comment by lucaszanella** [comment] 2018-02-16 04:58
The problem appears right after running what I've run in the pasted command on my post.

If it's a vmbuilder bug why it manifested only for me? I'm running Ubuntu 17.10.1 by the way.

(hey, is there a yaml file for building the linux kernel? couldn't find it anywhere and it's of great importance to build a kernel with gitian)

**Comment by josephbisch** [comment] 2018-02-16 12:02
This looks like a duplicate of #144.

I didn't make the connection when I first saw this bug report, but I believe this should be fixed already by #154. So if you are using the newroco fork of vmbuilder, which is [now the "official' vmbuilder](https://bugs.launchpad.net/ubuntu/+source/vm-builder/+bug/1260062/comments/15), then I don't think you should be experiencing this bug.

There isn't yet any yaml file (gitian descriptor) for any kernels afaik.

And since your problem with being logged out occurs with just running the `make-base-vm` command, I already know I can't reproduce the issue, because I've ran make-base-vm many times without experiencing that.

**Comment by lucaszanella** [comment] 2018-02-16 23:35
I don't understand. How should I use the new fork of vmbuilder? Shuldn't it just work since I did a git clone yesterday?

**Comment by josephbisch** [comment] 2018-02-16 23:48
I'm not sure how you installed vmbuilder, but just cloning the gitian-builder repo doesn't install vmbuilder. The fork of vmbuilder is in [this repo](https://github.com/newroco/vmbuilder). After cloning that you can do `python setup.py install` to install that version of vmbuilder.

**Comment by lucaszanella** [comment] 2018-02-16 23:54
Right, I forgot, I've just run

`sudo apt-get install git apache2 apt-cacher-ng python-vm-builder ruby qemu-utils`

as says in the README for ubuntu (which is 17.10.1 here)

**Comment by josephbisch** [comment] 2018-02-17 00:03
Oh, looks like I updated the vmbuilder info under the Arch Linux heading, but not the Ubuntu heading. I'll have to update the README to say to install the fork of vmbuilder instead of the python-vm-builder package.

**Comment by lucaszanella** [comment] 2018-02-17 05:43
Ok, thanks. I think I fixed it anyways, but why is this fork necessary? Is it mainly because of my reported problem?

Because I fixed my problem instead of installing the fork (it takes time to review sources, and this particular vmbuilder fork seems to have no reviewers). I'm getting this other error:

```
Checking if target is up..............................
ssh: connect to host localhost port 2223: Connection refused
/home/lz/gitian-builder/bin/gbuild:21:in `system!': failed to run on-target true (RuntimeError)
	from /home/lz/gitian-builder/bin/gbuild:73:in `build_one_configuration'
	from /home/lz/gitian-builder/bin/gbuild:299:in `block (2 levels) in <main>'
	from /home/lz/gitian-builder/bin/gbuild:294:in `each'
	from /home/lz/gitian-builder/bin/gbuild:294:in `block in <main>'
	from /home/lz/gitian-builder/bin/gbuild:292:in `each'
	from /home/lz/gitian-builder/bin/gbuild:292:in `<main>'
```

I don't think it's related to vmbuilder. Do you recognize it?

**Comment by lucaszanella** [comment] 2018-02-17 07:45
I guess I should post the entire thing:

```
/home/lz/gitian-builder/bin/gbuild linux.yml
sh: 1: cd: can't cd to inputs
--- Building for xenial amd64 ---
Stopping target if it is up
Making a new image copy
Formatting 'target-xenial-amd64.qcow2', fmt=qcow2 size=11811160064 backing_file=base-xenial-amd64.qcow2 cluster_size=65536 lazy_refcounts=off refcount_bits=16
Starting target
Checking if target is up..............................
ssh: connect to host localhost port 2223: Connection refused
/home/lz/gitian-builder/bin/gbuild:21:in `system!': failed to run on-target true (RuntimeError)
	from /home/lz/gitian-builder/bin/gbuild:73:in `build_one_configuration'
	from /home/lz/gitian-builder/bin/gbuild:299:in `block (2 levels) in <main>'
	from /home/lz/gitian-builder/bin/gbuild:294:in `each'
	from /home/lz/gitian-builder/bin/gbuild:294:in `block in <main>'
	from /home/lz/gitian-builder/bin/gbuild:292:in `each'
	from /home/lz/gitian-builder/bin/gbuild:292:in `<main>'
```

what does` sh: 1: cd: can't cd to inputs` means?

**Comment by lucaszanella** [comment] 2018-02-17 08:16
I also discovered that I have `start-target` but not `on-target` or `stop-target`

**Comment by josephbisch** [comment] 2018-02-17 14:06
All three of `start-target`, `on-target`, and `stop-target` should be there after you clone the gitian-builder repo (see https://github.com/devrandom/gitian-builder/tree/master/libexec). Maybe you deleted them?

The `can't cd to inputs` means that the inputs directory doesn't exist or isn't in the right location. Did you put the inputs directory within the gitian-builder directory? Maybe this has something to do with where you are running gbuild from? I usually run from the gitian-builder directory and then specify the path to the yaml file. Like: `./bin/gbuild /path/to/linux.yml`. Maybe the gitian-builder code uses a relative path for the cd and it doesn't work if you aren't in the gitian-builder directory. I haven't checked the code to verify whether that is the case.

**Comment by lucaszanella** [comment] 2018-02-17 15:06
@josephbisch right, I've run with the right paths and now it worked, but I'm still getting SSH conenction problems

```
lz@air:~/gitian-builder$ ./bin/gbuild /home/lz/Desktop/linux.yml
sha256sum: linux-4.16-rc1.tar.gz: No such file or directory
--- Building for xenial amd64 ---
Stopping target if it is up
Making a new image copy
Formatting 'target-xenial-amd64.qcow2', fmt=qcow2 size=11811160064 backing_file=base-xenial-amd64.qcow2 cluster_size=65536 lazy_refcounts=off refcount_bits=16
Starting target
Checking if target is up..............................
ssh: connect to host localhost port 2223: Connection refused
./bin/gbuild:21:in `system!': failed to run on-target true (RuntimeError)
	from ./bin/gbuild:73:in `build_one_configuration'
	from ./bin/gbuild:299:in `block (2 levels) in <main>'
	from ./bin/gbuild:294:in `each'
	from ./bin/gbuild:294:in `block in <main>'
	from ./bin/gbuild:292:in `each'
	from ./bin/gbuild:292:in `<main>'
```

**Comment by lucaszanella** [comment] 2018-02-17 15:08
@josephbisch this path thing is very confusing. Now I can't specify the full path to the linux-4.16-rc1.tar.gz. I should paste everything into the gitian-builder directory everytime I need it?

**Comment by showman621** [comment] 2020-02-23 16:57
> Am I doing something wrong? Tried with sudo and without sudo.
> 
> Also, a strange effect happens: whenever I press control C, my system logs off. Happened in my 2 computers after trying to install gitian
> 
> This is the output of `bin/make-base-vm --arch amd64`
> 
> ```
> ...
> Configuration file '/etc/sudoers'
>  ==> Modified (by you or by a script) since installation.
>  ==> Package distributor has shipped an updated version.
>    What would you like to do about it ?  Your options are:
>     Y or I  : install the package maintainer's version
>     N or O  : keep your currently-installed version
>       D     : show the differences between the versions
>       Z     : start a shell to examine the situation
>  The default action is to keep your current version.
> *** sudoers (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package sudo (--configure):
>  end of file on stdin at conffile prompt
> Setting up vim-common (2:7.4.1689-3ubuntu1.2) ...
> Setting up vim-tiny (2:7.4.1689-3ubuntu1.2) ...
> dpkg: dependency problems prevent configuration of ubuntu-minimal:
>  ubuntu-minimal depends on sudo; however:
>   Package sudo is not configured yet.
> 
> dpkg: error processing package ubuntu-minimal (--configure):
>  dependency problems - leaving unconfigured
> Setting up kbd (1.15.5-1ubuntu5) ...
> Setting up console-setup-linux (1.108ubuntu15.3) ...
> Installing new version of config file /etc/console-setup/compose.ISO-8859-1.inc ...
> Installing new version of config file /etc/console-setup/compose.ISO-8859-13.inc ...
> Installing new version of config file /etc/console-setup/compose.ISO-8859-14.inc ...
> Installing new version of config file /etc/console-setup/compose.ISO-8859-15.inc ...
> Installing new version of config file /etc/console-setup/compose.ISO-8859-2.inc ...
> Installing new version of config file /etc/console-setup/compose.ISO-8859-3.inc ...
> Installing new version of config file /etc/console-setup/compose.ISO-8859-4.inc ...
> Installing new version of config file /etc/console-setup/compose.ISO-8859-7.inc ...
> Installing new version of config file /etc/console-setup/compose.ISO-8859-9.inc ...
> Setting up console-setup (1.108ubuntu15.3) ...
> update-initramfs: deferring update (trigger activated)
> Processing triggers for libc-bin (2.23-0ubuntu10) ...
> Processing triggers for systemd (229-4ubuntu21.1) ...
> Processing triggers for ureadahead (0.100.0-19) ...
> Processing triggers for initramfs-tools (0.122ubuntu8.10) ...
> update-initramfs: Generating /boot/initrd.img-4.4.0-112-generic
> Processing triggers for resolvconf (1.78ubuntu6) ...
> Errors were encountered while processing:
>  sudo
>  ubuntu-minimal
> Extracting templates from packages: 100%
> W: --force-yes is deprecated, use one of the options starting with --allow instead.
> W: Can't drop privileges for downloading as file '/var/cache/apt/archives/partial/base-files_9.4ubuntu4.5_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```

I had tried
apt-get update
apt-get upgrade
And it worked hope it helps

**Comment by devrandom** [comment] 2020-08-30 11:46
stale

**Closed by devrandom** 2020-08-30 11:46 UTC
